### ISSUE TITLE
PRADA probabilistic planner progress tracking

### ISSUE THREAD

**Issue by gsaponaro** [robotology/poeticon#15]
In aa2008858140fd0a10528c81f63229b6dc70956a, I committed @AlexAntn 's work based on the PRADA probabilistic planner.

It is composed of two software bundles:
1. the actual planner module, planner.exe, which needs to sit in the same directory of these files: config, rules.dat, state.dat, symbols.dat (currently this directory is app/conf)
2. a bunch of Python scripts, which need access to these files (they can be anywhere on the system): Object_names-IDs.dat, pre_rules.dat, pre_symbols.dat, subgoals.dat

Tracker of improvements to make:
- [x] write planner installation instructions in https://github.com/robotology/poeticon (done, possibly they can be simplified/automated further)
- [ ] put planner.exe + its files in a dedicated directory instead of app/conf; rename the "config" file to avoid confusion with other modules' configurations
- [ ] the Python scripts should use ResourceFinder in order to locate the files to load/save, instead of using the current directory
- [ ] each Python script should create yarp ports with a clear prefix unique to that script, for example geometric_grounding.py should create ports called /geometricGrounding/* (or similar); ideally, the user should be able to override the default prefix with a --name parameter (this last thing has low priority)
- [ ] port names in the modules & XML launchers should use a consistent style, for example always [camelCase](http://en.wikipedia.org/wiki/CamelCase) or always names_with_underscore, not a mixture of the two
- [ ] stress test this thing :)

cc @lorejam @vicentepedro

**Comment by gsaponaro** [comment]
https://github.com/robotology/poeticon/pull/19 addressed some of these issues.

**Comment by gsaponaro** [comment]
#21 fixed keyboard interrupts (ctrl+c) in the Python scripts.

**Comment by gsaponaro** [comment]
#27 standardized port names of the Python scripts.

**Comment by gsaponaro** [comment]
88aa5221373225f4eba763bad21f0a050679192f standardized port names of C++ PRADA modules.
